apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: postgres
  name: postgres
  namespace: matrix
spec:
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    k8s-app: postgres
  sessionAffinity: None
  type: ClusterIP
