- name: Allow release info change
  lineinfile:
    path: /etc/apt/apt.conf.d/99releaseinfochange
    state: present
    create: yes
    line: Acquire::AllowReleaseInfoChange::Suite "true";

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    upgrade: full
