kind: Deployment
apiVersion: apps/v1
metadata:
  name: jitsi
  namespace: matrix
  labels:
    k8s-app: jitsi
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: jitsi
  template:
    metadata:
      name: jitsi
      creationTimestamp: null
      labels:
        k8s-app: jitsi
    spec:
      volumes:
        - name: jitsi-conf
          persistentVolumeClaim:
            claimName: jitsi-conf
      containers:
        - name: web
          image: jitsi/web:stable-7882
          envFrom:
            - configMapRef:
                name: jitsi-envs
          env:
            - name: DOCKER_HOST_ADDRESS
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: JVB_WS_SERVER_ID
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          resources: {}
          volumeMounts:
            - name: jitsi-conf
              mountPath: /config
              subPath: web-config
            - name: jitsi-conf
              mountPath: /var/spool/cron/crontabs
              subPath: crontabs
            - name: jitsi-conf
              mountPath: /usr/share/jitsi-meet/transcripts
              subPath: transcripts
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
        - name: prosody
          image: jitsi/prosody:stable-7882
          envFrom:
            - configMapRef:
                name: jitsi-envs
          resources: {}
          volumeMounts:
            - name: jitsi-conf
              mountPath: /config
              subPath: prosody-config
            - name: jitsi-conf
              mountPath: /prosody-plugins-custom
              subPath: prosody-plugins-custom
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
        - name: jicofo
          image: jitsi/jicofo:stable-7882
          envFrom:
            - configMapRef:
                name: jitsi-envs
          resources: {}
          volumeMounts:
            - name: jitsi-conf
              mountPath: /config
              subPath: jicofo-config
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
        - name: jvb
          image: jitsi/jvb:stable-7882
          envFrom:
            - configMapRef:
                name: jitsi-envs
          resources: {}
          volumeMounts:
            - name: jitsi-conf
              mountPath: /config
              subPath: jvb-config
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

